apiVersion: v1
kind: Service
metadata:
  name: laravel-app1-service
  labels:
    app: laravel-app1
spec:
  selector:
    app: laravel-app1
  type: NodePort
  ports:
    - nodePort: 31000
      port: 80
      targetPort: 3000